spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vincentmunene49/ecommerse-config-server
          clone-on-start: true

server:
  port: 9296

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

